
spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      schema: ${DB_USERNAME}
      # Optional Oracle-specific connection properties
      connection-init-sql: ALTER SESSION SET CURRENT_SCHEMA = ${DB_USERNAME}
      connection-test-query: SELECT 1 FROM DUAL

discord:
  bot:
    token: ${DISC_BOT_KEY}
    prefix: "!"
    intents:
      - GUILD_MESSAGES
      - GUILD_VOICE_STATES
      - GUILD_MEMBERS
      - GUILD_PRESENCES

# MyBatis Configuration
mybatis:
  mapper-locations: classpath:mappers/**/*.xml
  type-aliases-package: com.home.connections.dto
  configuration:
    map-underscore-to-camel-case: true
    default-statement-timeout: 30
    lazy-loading-enabled: true
    aggressive-lazy-loading: false

logging:
  level:
    root: INFO
    com.home.Connections: DEBUG
    org.springframework: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"



